repository: ocp-tests
variants:
 - name: okd
   attributes:
    - _artifacts/okd-attributes.adoc
   build: false
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - whats_new/**/*.adoc
       - installing/**/*.adoc
       - images/*.png
       - images/*.svg
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
 - name: openshift-container-platform
   attributes:
    - _artifacts/ocp-attributes.adoc
   build: true
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - release_notes/**/*.adoc
       - installing/**/*.adoc
       - images/*.png
       - images/*.svg
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - whats_new
       - getting_started
       - cloud_infrastructure_access
       - administering_a_cluster
 - name: openshift-dedicated
   attributes:
    - _artifacts/osd-attributes.adoc
   build: false
   files:
     included:
       - architecture/**/*.adoc
       - welcome/**/*.adoc
       - modules/**/*.adoc
       - getting_started/**/*.adoc
       - cloud_infrastructure_access/**/*.adoc
       - administering_a_cluster/**/*.adoc
       - images/*.png
       - images/*.svg
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - installing
       - whats_new
