repository: rhosak-documentation
variants:
 - name: rhosak-documentation
   attributes:
    - _artifacts/attributes.adoc
   build: true
   files:
     included:
       - assemblies/*.adoc
       - assemblies/**/*.adoc
       - modules/*.adoc
       - modules/**/*.adoc
       - _images/**/*.png
       - _images/**/*.svg 
